# Generated by Django 3.0.7 on 2020-06-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
    ]
